version: "3.2"
services:

  db:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    restart: always

  app:
    build:
      context: web_app
    ports:
      - "3000:8080"
    environment:
      - PORT
    restart: always